create table comtrades
(
    id              bigint generated by default as identity,
    date_time_start timestamp,
    date_time_stop  timestamp,
    station_name    varchar(255),
    primary key (id)
);

create table channels
(
    id          bigint generated by default as identity,
    a           double precision,
    b           double precision,
    ch_id       varchar(255),
    number      integer,
    type        varchar(255),
    unit        varchar(255),
    comtrade_id bigint,
    foreign key (comtrade_id) references comtrades (id),
    primary key (id)
);

create table readings
(
    id         bigint generated by default as identity,
    number     integer,
    val        double precision,
    channel_id bigint,
    foreign key (channel_id) references channels (id),
    primary key (id)
);